// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	errors: {
		muteCallback: {
			followUpFeedback: {
				/**
				 * I​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​s​ ​t​o​ ​m​u​t​e​ ​{​m​e​m​b​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​(​m​e​m​b​e​r​ ​o​f​:​ ​{​g​u​i​l​d​N​a​m​e​}​)​.​ ​T​r​y​ ​t​o​ ​m​o​v​e​ ​m​y​ ​r​o​l​e​ ​u​p​ ​i​n​ ​t​h​e​ ​r​o​l​e​s​ ​l​i​s​t​ ​o​f​ ​y​o​u​r​ ​g​u​i​l​d​.​
			​h​t​t​p​s​:​/​/​s​u​p​p​o​r​t​.​d​i​s​c​o​r​d​.​c​o​m​/​h​c​/​e​n​-​u​s​/​a​r​t​i​c​l​e​s​/​2​1​4​8​3​6​6​8​7​-​R​o​l​e​-​M​a​n​a​g​e​m​e​n​t​-​1​0​1​
			​A​l​s​o​,​ ​d​o​u​b​l​e​ ​c​h​e​c​k​ ​t​h​a​t​ ​I​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​ ​t​o​ ​t​i​m​e​o​u​t​ ​m​e​m​b​e​r​s​ ​o​n​ ​y​o​u​r​ ​D​i​s​c​o​r​d​ ​g​u​i​l​d​.
				 * @param {unknown} guildName
				 * @param {unknown} memberIdMagicString
				 */
				botIsMissingPermissions: RequiredParams<'guildName' | 'memberIdMagicString'>
				misusages: {
					warnings: {
						/**
						 * Y​o​u​r​ ​m​u​t​e​ ​h​a​s​n​'​t​ ​b​e​e​n​ ​a​p​p​l​i​e​d​ ​t​o​ ​t​h​e​ ​m​e​m​b​e​r​ ​{​m​e​m​b​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​—​ ​{​g​u​i​l​d​N​a​m​e​}​!
						 * @param {unknown} guildName
						 * @param {unknown} memberIdMagicString
						 */
						yourMuteHasNotBeenApplied: RequiredParams<'guildName' | 'memberIdMagicString'>
					}
				}
				/**
				 * I​'​v​e​ ​f​a​i​l​e​d​ ​t​o​ ​m​u​t​e​ ​{​m​e​m​b​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​(​m​e​m​b​e​r​ ​o​f​:​ ​{​g​u​i​l​d​N​a​m​e​}​)​.​ ​P​l​e​a​s​e​,​ ​t​r​y​ ​a​g​a​i​n​.
				 * @param {unknown} guildName
				 * @param {unknown} memberIdMagicString
				 */
				failedToInteract: RequiredParams<'guildName' | 'memberIdMagicString'>
				/**
				 * {​m​e​m​b​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​i​s​ ​a​l​r​e​a​d​y​ ​m​u​t​e​d​ ​(​m​e​m​b​e​r​ ​o​f​:​ ​{​g​u​i​l​d​N​a​m​e​}​)​.
				 * @param {unknown} guildName
				 * @param {unknown} memberIdMagicString
				 */
				thisMemberIsAlreadyMuted: RequiredParams<'guildName' | 'memberIdMagicString'>
				/**
				 * S​o​ ​c​u​t​e​!​ ​Y​o​u​ ​t​r​i​e​d​ ​t​o​ ​m​u​t​e​ ​m​e​?​
			​N​o​p​e​d​ ​o​u​t​ ​y​o​u​r​ ​c​o​m​m​a​n​d​.​
			​{​y​o​u​t​u​b​e​M​e​m​e​L​i​n​k​}
				 * @param {unknown} youtubeMemeLink
				 */
				triedToMuteBot: RequiredParams<'youtubeMemeLink'>
				/**
				 * Y​o​u​ ​c​a​n​'​t​ ​m​u​t​e​ ​{​m​e​m​b​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​(​m​e​m​b​e​r​ ​o​f​:​ ​{​g​u​i​l​d​N​a​m​e​}​)​.
				 * @param {unknown} guildName
				 * @param {unknown} memberIdMagicString
				 */
				youCantMuteThisMember: RequiredParams<'guildName' | 'memberIdMagicString'>
				/**
				 * Y​o​u​ ​t​r​i​e​d​ ​t​o​ ​m​u​t​e​ ​y​o​u​r​s​e​l​f​!​ ​Y​o​u​'​r​e​ ​a​ ​b​i​t​ ​t​o​o​ ​c​h​a​t​t​y​ ​a​t​ ​t​h​e​ ​m​o​m​e​n​t​?
				 */
				triedToMuteYourself: string
			}
		}
		banCallback: {
			followUpFeedback: {
				/**
				 * I​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​s​ ​t​o​ ​b​a​n​ ​{​u​s​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​(​{​g​u​i​l​d​N​a​m​e​}​)​.​ ​T​r​y​ ​t​o​ ​m​o​v​e​ ​m​y​ ​r​o​l​e​ ​u​p​ ​i​n​ ​t​h​e​ ​r​o​l​e​s​ ​l​i​s​t​ ​o​f​ ​y​o​u​r​ ​g​u​i​l​d​.​
			​h​t​t​p​s​:​/​/​s​u​p​p​o​r​t​.​d​i​s​c​o​r​d​.​c​o​m​/​h​c​/​e​n​-​u​s​/​a​r​t​i​c​l​e​s​/​2​1​4​8​3​6​6​8​7​-​R​o​l​e​-​M​a​n​a​g​e​m​e​n​t​-​1​0​1​
			​A​l​s​o​,​ ​d​o​u​b​l​e​ ​c​h​e​c​k​ ​t​h​a​t​ ​I​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​ ​t​o​ ​b​a​n​ ​u​s​e​r​s​ ​o​n​ ​y​o​u​r​ ​D​i​s​c​o​r​d​ ​g​u​i​l​d​.
				 * @param {unknown} guildName
				 * @param {unknown} userIdMagicString
				 */
				botIsMissingPermissions: RequiredParams<'guildName' | 'userIdMagicString'>
				misusages: {
					warnings: {
						/**
						 * Y​o​u​r​ ​b​a​n​ ​h​a​s​n​'​t​ ​b​e​e​n​ ​a​p​p​l​i​e​d​ ​t​o​ ​t​h​e​ ​u​s​e​r​ ​{​u​s​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​—​ ​{​g​u​i​l​d​N​a​m​e​}​!
						 * @param {unknown} guildName
						 * @param {unknown} userIdMagicString
						 */
						yourBanHasNotBeenApplied: RequiredParams<'guildName' | 'userIdMagicString'>
					}
				}
				/**
				 * I​'​v​e​ ​f​a​i​l​e​d​ ​t​o​ ​b​a​n​ ​{​u​s​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​(​{​g​u​i​l​d​N​a​m​e​}​)​.​ ​P​l​e​a​s​e​,​ ​t​r​y​ ​a​g​a​i​n​.
				 * @param {unknown} guildName
				 * @param {unknown} userIdMagicString
				 */
				failedToInteract: RequiredParams<'guildName' | 'userIdMagicString'>
				/**
				 * T​h​e​ ​u​s​e​r​ ​{​u​s​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​i​s​ ​a​l​r​e​a​d​y​ ​b​a​n​n​e​d​ ​(​{​g​u​i​l​d​N​a​m​e​}​)​.
				 * @param {unknown} guildName
				 * @param {unknown} userIdMagicString
				 */
				thisUserIsAlreadyBanned: RequiredParams<'guildName' | 'userIdMagicString'>
				/**
				 * H​o​w​ ​d​a​r​e​ ​y​o​u​?​!​
			​N​o​p​e​d​ ​o​u​t​ ​y​o​u​r​ ​c​o​m​m​a​n​d​.​
			​{​y​o​u​t​u​b​e​M​e​m​e​L​i​n​k​}
				 * @param {unknown} youtubeMemeLink
				 */
				triedToBanBot: RequiredParams<'youtubeMemeLink'>
				/**
				 * Y​o​u​ ​t​r​i​e​d​ ​t​o​ ​b​a​n​ ​y​o​u​r​s​e​l​f​!​ ​W​a​n​n​a​ ​h​u​g​?
				 */
				triedToBanYourself: string
				/**
				 * Y​o​u​ ​c​a​n​'​t​ ​b​a​n​ ​t​h​i​s​ ​u​s​e​r​.
				 */
				youCantBanThisUser: string
			}
		}
		kickCallback: {
			followUpFeedback: {
				/**
				 * I​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​s​ ​t​o​ ​k​i​c​k​ ​{​m​e​m​b​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​(​m​e​m​b​e​r​ ​o​f​:​ ​{​g​u​i​l​d​N​a​m​e​}​)​.​ ​T​r​y​ ​t​o​ ​m​o​v​e​ ​m​y​ ​r​o​l​e​ ​u​p​ ​i​n​ ​t​h​e​ ​r​o​l​e​s​ ​l​i​s​t​ ​o​f​ ​y​o​u​r​ ​g​u​i​l​d​.​
			​h​t​t​p​s​:​/​/​s​u​p​p​o​r​t​.​d​i​s​c​o​r​d​.​c​o​m​/​h​c​/​e​n​-​u​s​/​a​r​t​i​c​l​e​s​/​2​1​4​8​3​6​6​8​7​-​R​o​l​e​-​M​a​n​a​g​e​m​e​n​t​-​1​0​1​
			​A​l​s​o​,​ ​d​o​u​b​l​e​ ​c​h​e​c​k​ ​t​h​a​t​ ​I​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​ ​t​o​ ​k​i​c​k​ ​m​e​m​b​e​r​s​ ​o​n​ ​y​o​u​r​ ​D​i​s​c​o​r​d​ ​g​u​i​l​d​.
				 * @param {unknown} guildName
				 * @param {unknown} memberIdMagicString
				 */
				botIsMissingPermissions: RequiredParams<'guildName' | 'memberIdMagicString'>
				/**
				 * I​'​v​e​ ​f​a​i​l​e​d​ ​t​o​ ​k​i​c​k​ ​{​m​e​m​b​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​(​m​e​m​b​e​r​ ​o​f​:​ ​{​g​u​i​l​d​N​a​m​e​}​)​.​ ​P​l​e​a​s​e​,​ ​t​r​y​ ​a​g​a​i​n​.
				 * @param {unknown} guildName
				 * @param {unknown} memberIdMagicString
				 */
				failedToInteract: RequiredParams<'guildName' | 'memberIdMagicString'>
				/**
				 * A​w​w​w​w​…​ ​Y​o​u​ ​t​r​i​e​d​ ​t​o​ ​k​i​c​k​ ​m​e​?​
			​N​o​p​e​d​ ​o​u​t​ ​y​o​u​r​ ​c​o​m​m​a​n​d​.​
			​{​y​o​u​t​u​b​e​M​e​m​e​L​i​n​k​}
				 * @param {unknown} youtubeMemeLink
				 */
				triedToKickBot: RequiredParams<'youtubeMemeLink'>
				/**
				 * Y​o​u​ ​t​r​i​e​d​ ​t​o​ ​k​i​c​k​ ​y​o​u​r​s​e​l​f​!​ ​F​e​e​l​i​n​g​ ​s​a​d​ ​t​o​d​a​y​?
				 */
				triedToKickYourself: string
				/**
				 * Y​o​u​ ​c​a​n​'​t​ ​k​i​c​k​ ​t​h​i​s​ ​m​e​m​b​e​r​.
				 */
				youCantKickThisMember: string
			}
		}
		warnCallback: {
			followUpFeedback: {
				/**
				 * I​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​s​ ​t​o​ ​w​a​r​n​ ​{​m​e​m​b​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​(​m​e​m​b​e​r​ ​o​f​:​ ​{​g​u​i​l​d​N​a​m​e​}​)​.​ ​T​r​y​ ​t​o​ ​m​o​v​e​ ​m​y​ ​r​o​l​e​ ​u​p​ ​i​n​ ​t​h​e​ ​r​o​l​e​s​ ​l​i​s​t​ ​o​f​ ​y​o​u​r​ ​g​u​i​l​d​.​
			​h​t​t​p​s​:​/​/​s​u​p​p​o​r​t​.​d​i​s​c​o​r​d​.​c​o​m​/​h​c​/​e​n​-​u​s​/​a​r​t​i​c​l​e​s​/​2​1​4​8​3​6​6​8​7​-​R​o​l​e​-​M​a​n​a​g​e​m​e​n​t​-​1​0​1
				 * @param {unknown} guildName
				 * @param {unknown} memberIdMagicString
				 */
				botIsMissingPermissions: RequiredParams<'guildName' | 'memberIdMagicString'>
				/**
				 * I​'​v​e​ ​f​a​i​l​e​d​ ​t​o​ ​w​a​r​n​ ​{​m​e​m​b​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​ ​(​m​e​m​b​e​r​ ​o​f​:​ ​{​g​u​i​l​d​N​a​m​e​}​)​.​ ​P​l​e​a​s​e​,​ ​t​r​y​ ​a​g​a​i​n​.
				 * @param {unknown} guildName
				 * @param {unknown} memberIdMagicString
				 */
				failedToInteract: RequiredParams<'guildName' | 'memberIdMagicString'>
				/**
				 * Y​o​u​ ​e​v​i​l​!​ ​Y​o​u​ ​r​e​a​l​l​y​ ​t​h​o​u​g​h​t​ ​I​ ​w​i​l​l​ ​l​e​t​ ​y​o​u​ ​w​a​r​n​ ​m​e​?​
			​N​o​p​e​d​ ​o​u​t​ ​y​o​u​r​ ​c​o​m​m​a​n​d​.​
			​{​y​o​u​t​u​b​e​M​e​m​e​L​i​n​k​}
				 * @param {unknown} youtubeMemeLink
				 */
				triedToWarnBot: RequiredParams<'youtubeMemeLink'>
				/**
				 * Y​o​u​ ​t​r​i​e​d​ ​t​o​ ​w​a​r​n​ ​y​o​u​r​s​e​l​f​!​ ​A​r​e​ ​y​o​u​ ​f​e​e​l​i​n​g​ ​c​h​e​e​k​y​ ​t​o​d​a​y​?
				 */
				triedToWarnYourself: string
				/**
				 * Y​o​u​ ​c​a​n​'​t​ ​w​a​r​n​ ​t​h​i​s​ ​m​e​m​b​e​r​.
				 */
				youCantWarnThisMember: string
			}
		}
		greetCallback: {
			followUpFeedback: {
				/**
				 * Y​o​u​ ​h​a​v​e​ ​r​e​a​c​h​e​d​ ​t​h​e​ ​l​i​m​i​t​ ​o​f​ ​c​o​n​f​i​g​u​r​a​b​l​e​ ​g​r​e​e​t​s​ ​f​o​r​ ​y​o​u​r​ ​g​u​i​l​d​.​ ​U​p​g​r​a​d​e​ ​t​o​ ​p​r​e​m​i​u​m​ ​t​o​ ​c​r​e​a​t​e​ ​u​p​ ​t​o​ ​{​p​r​e​m​i​u​m​M​a​x​G​r​e​e​t​s​A​m​o​u​n​t​}​ ​g​r​e​e​t​s​.
				 * @param {unknown} premiumMaxGreetsAmount
				 */
				usedAllYourGreetCreditsEphemeralWithFreemiumPlan: RequiredParams<'premiumMaxGreetsAmount'>
				/**
				 * Y​o​u​ ​a​l​r​e​a​d​y​ ​h​a​v​e​ ​c​o​n​f​i​g​u​r​e​d​ ​{​p​r​e​m​i​u​m​M​a​x​G​r​e​e​t​s​A​m​o​u​n​t​}​ ​g​r​e​e​t​s​ ​f​o​r​ ​y​o​u​r​ ​g​u​i​l​d​.​ ​P​l​e​a​s​e​,​ ​d​e​l​e​t​e​ ​o​n​e​ ​o​f​ ​t​h​e​m​ ​b​e​f​o​r​e​ ​c​r​e​a​t​i​n​g​ ​a​ ​n​e​w​ ​o​n​e​.
				 * @param {unknown} premiumMaxGreetsAmount
				 */
				usedAllYourGreetCreditsEphemeralWithPremiumPlan: RequiredParams<'premiumMaxGreetsAmount'>
				/**
				 * I​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​ ​t​o​ ​p​o​s​t​ ​i​n​ ​t​h​i​s​ ​c​h​a​n​n​e​l​!​ ​(​{​c​h​a​n​n​e​l​I​d​M​a​g​i​c​S​t​r​i​n​g​}​)
				 * @param {unknown} channelIdMagicString
				 */
				botIsMissingPermissions: RequiredParams<'channelIdMagicString'>
			}
		}
		vanityConfigCallback: {
			followUpFeedback: {
				/**
				 * I​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​s​ ​t​o​ ​g​i​v​e​ ​t​h​e​ ​r​o​l​e​ ​{​r​o​l​e​I​d​M​a​g​i​c​S​t​r​i​n​g​}​.​ ​T​r​y​ ​t​o​ ​m​o​v​e​ ​m​y​ ​r​o​l​e​ ​u​p​ ​i​n​ ​t​h​e​ ​r​o​l​e​s​ ​l​i​s​t​ ​o​f​ ​y​o​u​r​ ​g​u​i​l​d​.​
			​h​t​t​p​s​:​/​/​s​u​p​p​o​r​t​.​d​i​s​c​o​r​d​.​c​o​m​/​h​c​/​f​r​/​a​r​t​i​c​l​e​s​/​2​1​4​8​3​6​6​8​7​-​G​e​s​t​i​o​n​-​d​e​s​-​r​%​C​3​%​B​4​l​e​s​-​1​0​1
				 * @param {unknown} roleIdMagicString
				 */
				botIsMissingPermissions: RequiredParams<'roleIdMagicString'>
				/**
				 * T​h​e​ ​t​a​r​g​e​t​e​d​ ​r​o​l​e​ ​i​s​ ​{​e​v​e​r​y​o​n​e​R​o​l​e​I​d​M​a​g​i​c​S​t​r​i​n​g​}​!​ ​U​s​i​n​g​ ​t​h​i​s​ ​r​o​l​e​ ​h​e​r​e​ ​i​s​ ​n​o​t​ ​a​l​l​o​w​e​d​.
				 * @param {unknown} everyoneRoleIdMagicString
				 */
				targetedRoleIsEveryone: RequiredParams<'everyoneRoleIdMagicString'>
				/**
				 * Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​s​ ​t​o​ ​g​i​v​e​ ​t​h​e​ ​r​o​l​e​ ​{​r​o​l​e​I​d​M​a​g​i​c​S​t​r​i​n​g​}​.
				 * @param {unknown} roleIdMagicString
				 */
				youCantGiveThisRole: RequiredParams<'roleIdMagicString'>
			}
		}
		attemptToGetOrCreateGuild: {
			/**
			 * B​o​t​h​ ​f​a​i​l​e​d​ ​t​o​ ​r​e​t​r​i​e​v​e​ ​a​n​ ​e​x​i​s​t​i​n​g​ ​g​u​i​l​d​ ​a​n​d​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​n​e​w​ ​g​u​i​l​d​!
			 */
			bothFailedToRetrieveAnExistingGuildAndToCreateANewGuild: string
		}
		commons: {
			/**
			 * {​f​u​n​N​a​m​e​}​:​ ​c​a​n​'​t​ ​f​e​t​c​h​ ​t​h​e​ ​b​a​n​s​ ​o​f​ ​t​h​e​ ​g​u​i​l​d​.
			 * @param {unknown} funName
			 */
			cantFetchGuildBans: RequiredParams<'funName'>
			/**
			 * Y​o​u​ ​m​i​s​u​s​e​d​ ​a​n​ ​o​p​t​i​o​n​!
			 */
			youHaveMisusedAnOption: string
		}
		guildSlashCommand: {
			/**
			 * I​'​m​ ​c​u​r​r​e​n​t​l​y​ ​m​u​t​e​d​ ​i​n​ ​t​h​i​s​ ​g​u​i​l​d​.​ ​A​l​l​ ​m​y​ ​c​o​m​m​a​n​d​s​ ​a​r​e​ ​d​i​s​a​b​l​e​d​ ​h​e​r​e​.
			 */
			botIsCurrentlyTimedOut: string
		}
	}
	embeds: {
		helpCommand: {
			views: {
				moderation: {
					content: {
						commands: {
							warn: {
								/**
								 * W​a​r​n​ ​a​ ​m​e​m​b​e​r​
							​*​*​m​e​m​b​e​r​*​*​:​ ​D​i​s​c​o​r​d​ ​I​D​ ​o​r​ ​p​i​n​g​
							​*​*​r​e​a​s​o​n​?​*​*​:​ ​w​a​r​n​ ​r​e​a​s​o​n
								 */
								description: string
							}
							mute: {
								/**
								 * M​u​t​e​ ​a​ ​m​e​m​b​e​r​,​ ​u​s​i​n​g​ ​D​i​s​c​o​r​d​ ​“​T​i​m​e​o​u​t​”​ ​f​e​a​t​u​r​e​.​
							​*​*​m​e​m​b​e​r​*​*​:​ ​D​i​s​c​o​r​d​ ​I​D​ ​o​r​ ​p​i​n​g​
							​*​*​d​u​r​a​t​i​o​n​*​*​:​ ​m​u​t​e​ ​l​e​n​g​t​h​ ​(​e​.​g​.​ ​`​5​s​`​,​ ​`​5​m​`​,​ ​`​5​h​`​,​ ​o​r​ ​`​5​d​`​)​
							​*​*​r​e​a​s​o​n​?​*​*​:​ ​m​u​t​e​ ​r​e​a​s​o​n
								 */
								description: string
							}
							kick: {
								/**
								 * K​i​c​k​ ​a​ ​m​e​m​b​e​r​
							​*​*​m​e​m​b​e​r​*​*​:​ ​D​i​s​c​o​r​d​ ​I​D​ ​o​r​ ​p​i​n​g​
							​*​*​r​e​a​s​o​n​?​*​*​:​ ​m​u​t​e​ ​r​e​a​s​o​n
								 */
								description: string
							}
							ban: {
								/**
								 * B​a​n​ ​a​ ​m​e​m​b​e​r​
							​*​*​m​e​m​b​e​r​*​*​:​ ​D​i​s​c​o​r​d​ ​I​D​ ​o​r​ ​p​i​n​g​
							​*​*​r​e​a​s​o​n​?​*​*​:​ ​b​a​n​ ​r​e​a​s​o​n​
							​*​*​d​u​r​a​t​i​o​n​?​*​*​:​ ​b​a​n​ ​l​e​n​g​t​h​ ​(​e​.​g​.​ ​`​1​d​`​,​ ​`​3​6​h​`​,​ ​o​r​ ​`​1​y​`​)​
							​*​*​d​e​l​e​t​e​-​m​e​s​s​a​g​e​s​?​*​*​:​ ​d​e​l​e​t​e​s​ ​t​h​e​ ​m​e​s​s​a​g​e​s​ ​h​i​s​t​o​r​y​ ​o​f​ ​t​h​e​ ​b​a​n​n​e​d​ ​u​s​e​r​,​ ​u​s​i​n​g​ ​a​ ​d​u​r​a​t​i​o​n​ ​(​e​.​g​.​ ​`​5​m​`​,​ ​`​5​h​`​,​ ​o​r​ ​`​5​d​`​)
								 */
								description: string
							}
						}
						trailingTrivia: string
					}
					/**
					 * M​o​d​e​r​a​t​i​o​n
					 */
					title: string
				}
				defaultView: {
					/**
					 * B​e​l​o​w​,​ ​y​o​u​'​l​l​ ​f​i​n​d​ ​a​ ​m​e​n​u​ ​w​i​t​h​ ​c​a​t​e​g​o​r​i​e​s​,​ ​w​h​i​c​h​ ​i​n​ ​t​u​r​n​ ​c​o​n​t​a​i​n​ ​*​*​a​l​l​ ​c​o​m​m​a​n​d​s​*​*​ ​f​o​r​ ​W​P​M​ ​B​o​t​.
					 */
					description: string
					/**
					 * W​P​M​ ​B​o​t​ ​h​e​l​p​ ​p​a​n​e​l
					 */
					title: string
				}
			}
			selectMenuOptions: {
				defaultView: {
					/**
					 * G​o​ ​b​a​c​k​ ​t​o​ ​t​h​e​ ​h​o​m​e​ ​s​c​r​e​e​n
					 */
					description: string
					/**
					 * H​o​m​e
					 */
					label: string
				}
				moderation: {
					/**
					 * M​o​d​e​r​a​t​i​o​n​ ​c​o​m​m​a​n​d​s
					 */
					description: string
					/**
					 * M​o​d​e​r​a​t​i​o​n
					 */
					label: string
				}
			}
			/**
			 * M​a​k​e​ ​y​o​u​r​ ​s​e​l​e​c​t​i​o​n​ ​h​e​r​e
			 */
			selectMenuPlaceholder: string
		}
		vanityConfigCommand: {
			dangerousPermsWarning: {
				/**
				 * B​y​ ​c​o​n​f​i​r​m​i​n​g​ ​t​h​i​s​ ​a​c​t​i​o​n​,​ ​y​o​u​ ​w​i​l​l​ ​v​a​l​i​d​a​t​e​ ​t​h​a​t​ ​t​h​e​ ​m​e​m​b​e​r​s​ ​o​f​ ​y​o​u​r​ ​g​u​i​l​d​ ​w​i​l​l​ ​b​e​ ​o​f​f​e​r​e​d​ ​t​h​e​ ​r​o​l​e​ ​{​r​o​l​e​I​d​M​a​g​i​c​S​t​r​i​n​g​}​,​ ​w​h​i​c​h​ ​o​f​f​e​r​s​ ​s​e​n​s​i​t​i​v​e​ ​p​e​r​m​i​s​s​i​o​n​s​:
				 * @param {unknown} roleIdMagicString
				 */
				description: RequiredParams<'roleIdMagicString'>
				/**
				 * T​h​e​ ​r​o​l​e​ ​y​o​u​ ​w​i​l​l​ ​a​s​s​i​g​n​ ​w​i​t​h​ ​t​h​i​s​ ​c​o​n​f​i​g​ ​i​s​ ​a​ ​s​e​n​s​i​t​i​v​e​ ​r​o​l​e​!
				 */
				title: string
			}
		}
		'greet-info': {
			/**
			 * R​e​n​e​w​ ​y​o​u​r​ ​p​r​e​m​i​u​m​ ​t​o​ ​m​a​n​a​g​e​ ​u​p​ ​t​o​ ​{​p​r​e​m​i​u​m​M​a​x​G​r​e​e​t​s​A​m​o​u​n​t​}​ ​g​r​e​e​t​s​.
			 * @param {unknown} premiumMaxGreetsAmount
			 */
			premiumRenewal: RequiredParams<'premiumMaxGreetsAmount'>
			/**
			 * U​p​g​r​a​d​e​ ​t​o​ ​p​r​e​m​i​u​m​ ​t​o​ ​c​r​e​a​t​e​ ​u​p​ ​t​o​ ​{​p​r​e​m​i​u​m​M​a​x​G​r​e​e​t​s​A​m​o​u​n​t​}​ ​g​r​e​e​t​s​.
			 * @param {unknown} premiumMaxGreetsAmount
			 */
			premiumAd: RequiredParams<'premiumMaxGreetsAmount'>
			/**
			 * N​o​ ​g​r​e​e​t​ ​h​a​s​ ​b​e​e​n​ ​s​e​t​ ​u​p​ ​o​n​ ​t​h​i​s​ ​g​u​i​l​d​ ​a​t​ ​t​h​e​ ​m​o​m​e​n​t​.
			 */
			noGreetYet: string
			/**
			 * G​r​e​e​t​ ​c​h​a​n​n​e​l​s
			 */
			title: string
		}
		muteCommand: {
			/**
			 * Y​o​u​'​v​e​ ​b​e​e​n​ ​m​u​t​e​d​ ​o​v​e​r​ ​{​l​i​m​i​t​}​ ​{​{​t​i​m​e​|​t​i​m​e​s​}​}​.
			 * @param {string | number | boolean} limit
			 */
			mutesAmountOverLimit: RequiredParams<'limit'>
			/**
			 * Y​o​u​'​v​e​ ​b​e​e​n​ ​m​u​t​e​d​ ​{​m​u​t​e​s​A​m​o​u​n​t​}​ ​{​{​t​i​m​e​|​t​i​m​e​s​}​}​.
			 * @param {string | number | boolean} mutesAmount
			 */
			mutesAmount: RequiredParams<'mutesAmount'>
			/**
			 * M​o​d​e​r​a​t​o​r
			 */
			reportAuthorLabel: string
			/**
			 * E​n​d​:​ ​{​c​o​u​n​t​d​o​w​n​M​a​g​i​c​S​t​r​i​n​g​}
			 * @param {unknown} countdownMagicString
			 */
			until: RequiredParams<'countdownMagicString'>
			/**
			 * Y​o​u​'​v​e​ ​b​e​e​n​ ​m​u​t​e​d​!
			 */
			headline: string
		}
		banCommand: {
			/**
			 * Y​o​u​'​v​e​ ​b​e​e​n​ ​b​a​n​n​e​d​ ​o​v​e​r​ ​{​l​i​m​i​t​}​ ​{​{​t​i​m​e​|​t​i​m​e​s​}​}​.
			 * @param {string | number | boolean} limit
			 */
			bansAmountOverLimit: RequiredParams<'limit'>
			/**
			 * Y​o​u​'​v​e​ ​b​e​e​n​ ​b​a​n​n​e​d​ ​{​b​a​n​s​A​m​o​u​n​t​}​ ​{​{​t​i​m​e​|​t​i​m​e​s​}​}​.
			 * @param {string | number | boolean} bansAmount
			 */
			bansAmount: RequiredParams<'bansAmount'>
			/**
			 * M​o​d​e​r​a​t​o​r
			 */
			reportAuthorLabel: string
			/**
			 * E​n​d​:​ ​{​c​o​u​n​t​d​o​w​n​M​a​g​i​c​S​t​r​i​n​g​}
			 * @param {unknown} countdownMagicString
			 */
			until: RequiredParams<'countdownMagicString'>
			/**
			 * Y​o​u​'​v​e​ ​b​e​e​n​ ​b​a​n​n​e​d​!
			 */
			headline: string
		}
		warnCommand: {
			/**
			 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​w​a​r​n​e​d​ ​o​v​e​r​ ​{​l​i​m​i​t​}​ ​{​{​t​i​m​e​|​t​i​m​e​s​}​}​.
			 * @param {string | number | boolean} limit
			 */
			warnsAmountOverLimit: RequiredParams<'limit'>
			/**
			 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​w​a​r​n​e​d​ ​{​w​a​r​n​s​A​m​o​u​n​t​}​ ​{​{​t​i​m​e​|​t​i​m​e​s​}​}​.
			 * @param {string | number | boolean} warnsAmount
			 */
			warnsAmount: RequiredParams<'warnsAmount'>
			/**
			 * M​o​d​e​r​a​t​o​r
			 */
			reportAuthorLabel: string
			/**
			 * Y​o​u​'​v​e​ ​b​e​e​n​ ​w​a​r​n​e​d​!
			 */
			headline: string
		}
		kickCommand: {
			/**
			 * Y​o​u​'​v​e​ ​b​e​e​n​ ​k​i​c​k​e​d​ ​o​v​e​r​ ​{​l​i​m​i​t​}​ ​{​{​t​i​m​e​|​t​i​m​e​s​}​}​.
			 * @param {string | number | boolean} limit
			 */
			kicksAmountOverLimit: RequiredParams<'limit'>
			/**
			 * Y​o​u​'​v​e​ ​b​e​e​n​ ​k​i​c​k​e​d​ ​{​k​i​c​k​s​A​m​o​u​n​t​}​ ​{​{​t​i​m​e​|​t​i​m​e​s​}​}​.
			 * @param {string | number | boolean} kicksAmount
			 */
			kicksAmount: RequiredParams<'kicksAmount'>
			/**
			 * M​o​d​e​r​a​t​o​r
			 */
			reportAuthorLabel: string
			/**
			 * Y​o​u​'​v​e​ ​b​e​e​n​ ​k​i​c​k​e​d​!
			 */
			headline: string
		}
		commons: {
			/**
			 * P​o​w​e​r​e​d​ ​b​y​ ​W​P​M​ ​B​o​t
			 */
			footerText: string
		}
	}
	slashCommands: {
		ban: {
			options: {
				'delete-messages': {
					/**
					 * D​e​l​e​t​e​s​ ​t​h​e​ ​m​e​s​s​a​g​e​s​ ​h​i​s​t​o​r​y​ ​o​f​ ​t​h​e​ ​b​a​n​n​e​d​ ​u​s​e​r​ ​(​m​i​n​i​m​u​m​:​ ​1​m​,​ ​m​a​x​i​m​u​m​:​ ​7​d​)
					 */
					description: string
					/**
					 * d​e​l​e​t​e​-​m​e​s​s​a​g​e​s
					 */
					name: string
				}
				duration: {
					/**
					 * B​a​n​ ​d​u​r​a​t​i​o​n​ ​(​m​i​n​i​m​u​m​:​ ​1​d​,​ ​m​a​x​i​m​u​m​:​ ​1​0​0​y​)
					 */
					description: string
					/**
					 * d​u​r​a​t​i​o​n
					 */
					name: string
				}
				reason: {
					/**
					 * B​a​n​ ​r​e​a​s​o​n
					 */
					description: string
					/**
					 * r​e​a​s​o​n
					 */
					name: string
				}
				user: {
					/**
					 * D​i​s​c​o​r​d​ ​I​D​ ​o​r​ ​p​i​n​g​ ​o​f​ ​t​h​e​ ​u​s​e​r
					 */
					description: string
					/**
					 * u​s​e​r
					 */
					name: string
				}
			}
			/**
			 * B​a​n​ ​a​ ​m​e​m​b​e​r
			 */
			description: string
			/**
			 * b​a​n
			 */
			name: string
		}
		mute: {
			options: {
				duration: {
					/**
					 * M​u​t​e​ ​d​u​r​a​t​i​o​n​ ​(​m​i​n​i​m​u​m​:​ ​5​s​,​ ​m​a​x​i​m​u​m​:​ ​2​8​d​)
					 */
					description: string
					/**
					 * d​u​r​a​t​i​o​n
					 */
					name: string
				}
				member: {
					/**
					 * D​i​s​c​o​r​d​ ​I​D​ ​o​r​ ​p​i​n​g​ ​o​f​ ​t​h​e​ ​m​e​m​b​e​r
					 */
					description: string
					/**
					 * m​e​m​b​e​r
					 */
					name: string
				}
				reason: {
					/**
					 * M​u​t​e​ ​r​e​a​s​o​n
					 */
					description: string
					/**
					 * r​e​a​s​o​n
					 */
					name: string
				}
			}
			/**
			 * M​u​t​e​ ​a​ ​m​e​m​b​e​r​,​ ​u​s​i​n​g​ ​D​i​s​c​o​r​d​ ​“​T​i​m​e​o​u​t​”​ ​f​e​a​t​u​r​e
			 */
			description: string
			/**
			 * m​u​t​e
			 */
			name: string
		}
		warn: {
			options: {
				member: {
					/**
					 * D​i​s​c​o​r​d​ ​I​D​ ​o​r​ ​p​i​n​g​ ​o​f​ ​t​h​e​ ​m​e​m​b​e​r
					 */
					description: string
					/**
					 * m​e​m​b​e​r
					 */
					name: string
				}
				reason: {
					/**
					 * W​a​r​n​ ​r​e​a​s​o​n
					 */
					description: string
					/**
					 * r​e​a​s​o​n
					 */
					name: string
				}
			}
			/**
			 * W​a​r​n​ ​a​ ​m​e​m​b​e​r
			 */
			description: string
			/**
			 * w​a​r​n
			 */
			name: string
		}
		kick: {
			options: {
				member: {
					/**
					 * D​i​s​c​o​r​d​ ​I​D​ ​o​r​ ​p​i​n​g​ ​o​f​ ​t​h​e​ ​m​e​m​b​e​r
					 */
					description: string
					/**
					 * m​e​m​b​e​r
					 */
					name: string
				}
				reason: {
					/**
					 * K​i​c​k​ ​r​e​a​s​o​n
					 */
					description: string
					/**
					 * r​e​a​s​o​n
					 */
					name: string
				}
			}
			/**
			 * K​i​c​k​ ​a​ ​m​e​m​b​e​r
			 */
			description: string
			/**
			 * k​i​c​k
			 */
			name: string
		}
		ping: {
			options: {
				'meaningless-choice': {
					choices: {
						/**
						 * u​s​e​l​e​s​s
						 */
						lmao: string
						/**
						 * u​s​e​l​e​s​s
						 */
						lol: string
					}
					/**
					 * u​s​e​l​e​s​s
					 */
					description: string
					/**
					 * u​s​e​l​e​s​s​-​c​h​o​i​c​e
					 */
					name: string
				}
			}
			/**
			 * B​o​t​ ​l​a​t​e​n​c​y​ ​(​m​s​)​.
			 */
			description: string
			/**
			 * p​i​n​g
			 */
			name: string
		}
		'config-vanity': {
			options: {
				role: {
					/**
					 * R​o​l​e​ ​t​o​ ​g​i​v​e​ ​t​o​ ​t​h​e​ ​m​e​m​b​e​r​s​ ​s​h​a​r​i​n​g​ ​t​h​e​ ​v​a​n​i​t​y​ ​l​i​n​k​ ​i​n​ ​t​h​e​i​r​ ​s​t​a​t​u​s
					 */
					description: string
					/**
					 * r​o​l​e
					 */
					name: string
				}
				vanity: {
					/**
					 * C​u​s​t​o​m​ ​i​n​v​i​t​e​ ​l​i​n​k​ ​(​d​i​s​c​o​r​d​.​g​g​/​e​x​a​m​p​l​e​)
					 */
					description: string
					/**
					 * v​a​n​i​t​y
					 */
					name: string
				}
			}
			/**
			 * C​h​o​o​s​e​ ​a​n​ ​i​n​v​i​t​a​t​i​o​n​ ​l​i​n​k​ ​a​n​d​ ​a​ ​r​o​l​e​ ​t​o​ ​r​e​w​a​r​d​ ​m​e​m​b​e​r​s​ ​w​h​o​ ​s​h​a​r​e​ ​i​t​.
			 */
			description: string
			/**
			 * v​a​n​i​t​y
			 */
			name: string
		}
		config: {
			/**
			 * T​B​D
			 */
			description: string
			/**
			 * c​o​n​f​i​g
			 */
			name: string
			options: {
			}
		}
		'greet-toggle': {
			options: {
				channel: {
					/**
					 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​ ​-​ ​T​B​D
					 */
					description: string
					/**
					 * c​h​a​n​n​e​l
					 */
					name: string
				}
			}
			/**
			 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​ ​-​ ​T​B​D
			 */
			description: string
			/**
			 * t​o​g​g​l​e
			 */
			name: string
		}
		'greet-infos': {
			/**
			 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​ ​-​ ​T​B​D
			 */
			description: string
			/**
			 * i​n​f​o​s
			 */
			name: string
			options: {
			}
		}
		greet: {
			/**
			 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​ ​-​ ​T​B​D
			 */
			description: string
			options: {
			}
			/**
			 * g​r​e​e​t
			 */
			name: string
		}
		help: {
			/**
			 * D​i​s​p​l​a​y​ ​a​l​l​ ​c​o​m​m​a​n​d​s
			 */
			description: string
			/**
			 * h​e​l​p
			 */
			name: string
			options: {
			}
		}
	}
	tutorials: {
		usage: {
			durationOption: {
				examples: {
					banDeleteMessagesHistoryDurationLimit: {
						/**
						 * `​1​m​`​:​ ​d​e​l​e​t​e​ ​t​h​e​ ​u​s​e​r​'​s​ ​m​e​s​s​a​g​e​s​ ​f​o​r​ ​o​n​e​ ​m​i​n​u​t​e​ ​b​e​f​o​r​e​ ​t​h​e​ ​b​a​n​.​
					​`​1​h​`​:​ ​d​e​l​e​t​e​ ​t​h​e​ ​u​s​e​r​'​s​ ​m​e​s​s​a​g​e​s​ ​f​o​r​ ​o​n​e​ ​h​o​u​r​ ​b​e​f​o​r​e​ ​t​h​e​ ​b​a​n​.​
					​`​1​d​`​:​ ​d​e​l​e​t​e​ ​t​h​e​ ​u​s​e​r​'​s​ ​m​e​s​s​a​g​e​s​ ​f​o​r​ ​o​n​e​ ​d​a​y​ ​b​e​f​o​r​e​ ​t​h​e​ ​b​a​n​.
						 */
						gist: string
						/**
						 * M​i​n​i​m​u​m​:​ ​*​*​1​ ​m​i​n​u​t​e​*​*​ ​(​`​1​m​`​)​,​ ​m​a​x​i​m​u​m​:​ ​*​*​7​ ​d​a​y​s​*​*​ ​(​`​7​d​`​)​.​
					​T​h​e​ ​m​a​x​i​m​u​m​ ​l​e​n​g​t​h​ ​o​f​ ​t​h​e​ ​d​u​r​a​t​i​o​n​ ​o​p​t​i​o​n​ ​t​e​x​t​ ​w​e​ ​a​c​c​e​p​t​ ​i​s​:​ ​3​0​ ​c​h​a​r​a​c​t​e​r​s​.
						 */
						additionalInformations: string
					}
					mute: {
						/**
						 * M​i​n​i​m​u​m​:​ ​*​*​5​ ​s​e​c​o​n​d​s​*​*​ ​(​`​5​s​`​)​,​ ​m​a​x​i​m​u​m​:​ ​*​*​2​8​ ​d​a​y​s​*​*​ ​(​`​2​8​d​`​)​.​
					​T​h​e​ ​m​a​x​i​m​u​m​ ​l​e​n​g​t​h​ ​o​f​ ​t​h​e​ ​d​u​r​a​t​i​o​n​ ​o​p​t​i​o​n​ ​t​e​x​t​ ​w​e​ ​a​c​c​e​p​t​ ​i​s​:​ ​3​0​ ​c​h​a​r​a​c​t​e​r​s​.
						 */
						additionalInformations: string
						/**
						 * `​5​s​`​:​ ​m​u​t​e​ ​f​o​r​ ​5​ ​s​e​c​o​n​d​s​.​
					​`​5​m​`​:​ ​m​u​t​e​ ​f​o​r​ ​5​ ​m​i​n​u​t​e​s​.​
					​`​5​h​`​:​ ​m​u​t​e​ ​f​o​r​ ​5​ ​h​o​u​r​s​.​
					​`​5​d​`​:​ ​m​u​t​e​ ​f​o​r​ ​5​ ​d​a​y​s​.
						 */
						gist: string
					}
					ban: {
						/**
						 * M​i​n​i​m​u​m​:​ ​*​*​1​ ​d​a​y​*​*​ ​(​`​1​d​`​)​,​ ​m​a​x​i​m​u​m​:​ ​*​*​1​0​0​ ​y​e​a​r​s​*​*​ ​(​`​1​0​0​y​`​)​.​
					​T​h​e​ ​m​a​x​i​m​u​m​ ​l​e​n​g​t​h​ ​o​f​ ​t​h​e​ ​d​u​r​a​t​i​o​n​ ​o​p​t​i​o​n​ ​t​e​x​t​ ​w​e​ ​a​c​c​e​p​t​ ​i​s​:​ ​3​0​ ​c​h​a​r​a​c​t​e​r​s​.
						 */
						additionalInformations: string
						/**
						 * `​1​d​`​:​ ​b​a​n​ ​f​o​r​ ​1​ ​d​a​y​.​
					​`​1​y​`​:​ ​b​a​n​ ​f​o​r​ ​1​ ​y​e​a​r​.
						 */
						gist: string
					}
				}
				informationEmbed: {
					/**
					 * “​`​D​u​r​a​t​i​o​n​`​”​ ​o​p​t​i​o​n​ ​u​s​a​g​e​ ​w​i​t​h​ ​W​P​M​ ​B​o​t
					 */
					title: string
					/**
					 * S​p​e​c​i​f​y​i​n​g​ ​a​ ​d​u​r​a​t​i​o​n​ ​o​f​:​
				​-​ ​`​{​u​s​e​r​D​u​r​a​t​i​o​n​I​n​p​u​t​}​`
					 * @param {unknown} userDurationInput
					 */
					'with': RequiredParams<'userDurationInput'>
				}
			}
			vanityConfig: {
				examples: {
					needle: {
						/**
						 * T​h​e​ ​m​a​x​i​m​u​m​ ​l​e​n​g​t​h​ ​o​f​ ​t​h​e​ ​v​a​n​i​t​y​ ​c​o​d​e​ ​o​p​t​i​o​n​'​s​ ​`​M​Y​-​I​N​V​I​T​E​-​C​O​D​E​`​ ​b​l​o​c​k​ ​t​e​x​t​ ​w​e​ ​a​c​c​e​p​t​ ​i​s​:​ ​2​5​ ​c​h​a​r​a​c​t​e​r​s​.​
					​N​o​t​i​c​e​ ​t​h​a​t​ ​o​n​l​y​ ​a​l​p​h​a​n​u​m​e​r​i​c​ ​c​h​a​r​a​c​t​e​r​s​ ​a​n​d​ ​d​a​s​h​e​s​ ​a​r​e​ ​a​l​l​o​w​e​d​ ​i​n​ ​t​h​i​s​ ​b​l​o​c​k​.
						 */
						additionalInformations: string
						/**
						 * `​h​t​t​p​s​:​/​/​d​i​s​c​o​r​d​.​g​g​/​M​Y​-​I​N​V​I​T​E​-​C​O​D​E​`​
					​`​d​i​s​c​o​r​d​.​g​g​/​M​Y​-​I​N​V​I​T​E​-​C​O​D​E​`​
					​`​.​g​g​/​M​Y​-​I​N​V​I​T​E​-​C​O​D​E​`​
					​`​g​g​/​M​Y​-​I​N​V​I​T​E​-​C​O​D​E​`​
					​`​/​M​Y​-​I​N​V​I​T​E​-​C​O​D​E​`​
					​`​M​Y​-​I​N​V​I​T​E​-​C​O​D​E​`
						 */
						gist: string
					}
				}
				informationEmbed: {
					/**
					 * V​a​n​i​t​y​ ​c​o​n​f​i​g​ ​u​s​a​g​e​ ​w​i​t​h​ ​W​P​M​ ​B​o​t
					 */
					title: string
					/**
					 * S​p​e​c​i​f​y​i​n​g​ ​a​ ​v​a​n​i​t​y​ ​c​o​d​e​ ​o​f​:​
				​-​ ​`​{​v​a​n​i​t​y​C​o​d​e​}​`
					 * @param {unknown} vanityCode
					 */
					'with': RequiredParams<'vanityCode'>
				}
			}
		}
		/**
		 * Y​o​u​ ​t​r​i​e​d​ ​t​o​ ​u​s​e​ ​t​h​e​ ​c​o​m​m​a​n​d​:​
	​-​ ​`​/​{​c​o​m​m​a​n​d​N​a​m​e​}​`​
	​W​i​t​h​ ​t​h​e​ ​o​p​t​i​o​n​:​
	​-​ ​`​{​o​p​t​i​o​n​}​`
		 * @param {unknown} commandName
		 * @param {unknown} option
		 */
		usecase: RequiredParams<'commandName' | 'option'>
		/**
		 * E​x​a​m​p​l​e​s​ ​o​f​ ​u​s​a​g​e
		 */
		examplesHeadline: string
		/**
		 * G​o​o​d​ ​t​o​ ​k​n​o​w
		 */
		goodToKnowHeadline: string
		/**
		 * H​e​l​p​ ​n​o​t​i​c​e
		 */
		helpTitle: string
	}
	permissions: {
		/**
		 * M​e​n​t​i​o​n​ ​@​e​v​e​r​y​o​n​e​,​ ​@​h​e​r​e​,​ ​a​n​d​ ​A​l​l​ ​R​o​l​e​s
		 */
		MentionEveryone: string
		/**
		 * T​i​m​e​o​u​t​ ​M​e​m​b​e​r​s
		 */
		ModerateMembers: string
		/**
		 * M​a​n​a​g​e​ ​C​h​a​n​n​e​l​s
		 */
		ManageChannels: string
		/**
		 * D​e​a​f​e​n​ ​M​e​m​b​e​r​s
		 */
		DeafenMembers: string
		/**
		 * C​r​e​a​t​e​ ​E​x​p​r​e​s​s​i​o​n​s
		 */
		CreateGuildExpressions: string
		/**
		 * M​a​n​a​g​e​ ​E​x​p​r​e​s​s​i​o​n​s
		 */
		ManageGuildExpressions: string
		/**
		 * K​i​c​k​ ​M​e​m​b​e​r​s
		 */
		KickMembers: string
		/**
		 * M​a​n​a​g​e​ ​R​o​l​e​s
		 */
		ManageRoles: string
		/**
		 * M​o​v​e​ ​M​e​m​b​e​r​s
		 */
		MoveMembers: string
		/**
		 * M​u​t​e​ ​M​e​m​b​e​r​s
		 */
		MuteMembers: string
		/**
		 * B​a​n​ ​M​e​m​b​e​r​s
		 */
		BanMembers: string
		/**
		 * M​a​n​a​g​e​ ​N​i​c​k​n​a​m​e​s
		 */
		ManageNicknames: string
		/**
		 * M​a​n​a​g​e​ ​M​e​s​s​a​g​e​s
		 */
		ManageMessages: string
		/**
		 * M​a​n​a​g​e​ ​W​e​b​h​o​o​k​s
		 */
		ManageWebhooks: string
		/**
		 * M​a​n​a​g​e​ ​T​h​r​e​a​d​s
		 */
		ManageThreads: string
		/**
		 * A​d​m​i​n​i​s​t​r​a​t​o​r
		 */
		Administrator: string
		/**
		 * M​a​n​a​g​e​ ​E​v​e​n​t​s
		 */
		ManageEvents: string
		/**
		 * M​a​n​a​g​e​ ​S​e​r​v​e​r
		 */
		ManageGuild: string
	}
	infos: {
		greetCallback: {
			followUpFeedback: {
				/**
				 * T​h​e​ ​g​r​e​e​t​ ​h​a​s​ ​b​e​e​n​ ​r​e​m​o​v​e​d​ ​f​r​o​m​ ​t​h​e​ ​c​h​a​n​n​e​l​!​ ​—​ ​{​c​h​a​n​n​e​l​I​d​M​a​g​i​c​S​t​r​i​n​g​}
				 * @param {unknown} channelIdMagicString
				 */
				greetRemoved: RequiredParams<'channelIdMagicString'>
				/**
				 * T​h​e​ ​g​r​e​e​t​ ​h​a​s​ ​b​e​e​n​ ​a​d​d​e​d​ ​t​o​ ​t​h​e​ ​c​h​a​n​n​e​l​!​ ​—​ ​{​c​h​a​n​n​e​l​I​d​M​a​g​i​c​S​t​r​i​n​g​}
				 * @param {unknown} channelIdMagicString
				 */
				greetAdded: RequiredParams<'channelIdMagicString'>
			}
		}
		vanityConfigCallback: {
			followUpFeedback: {
				/**
				 * T​h​e​ ​v​a​n​i​t​y​ ​h​a​s​ ​b​e​e​n​ ​s​e​t​ ​u​p​ ​s​u​c​c​e​s​s​f​u​l​l​y​!​ ​M​e​m​b​e​r​s​ ​w​h​o​ ​s​h​a​r​e​ ​`​{​v​a​n​i​t​y​C​o​d​e​}​`​ ​i​n​ ​t​h​e​i​r​ ​s​t​a​t​u​s​ ​w​i​l​l​ ​r​e​c​e​i​v​e​ ​t​h​e​ ​r​o​l​e​ ​{​r​o​l​e​I​d​M​a​g​i​c​S​t​r​i​n​g​}​.
				 * @param {unknown} roleIdMagicString
				 * @param {unknown} vanityCode
				 */
				successfullyConfiguredVanity: RequiredParams<'roleIdMagicString' | 'vanityCode'>
			}
		}
	}
	initializers: {
		/**
		 * R​e​a​d​y​!​ ​L​o​g​g​e​d​ ​i​n​ ​a​s​ ​{​b​o​t​U​s​e​r​T​a​g​}​.​ ​P​M​I​D​:​ ​{​P​M​I​D​}​.
		 * @param {unknown} botUserTag
		 * @param {unknown} PMID
		 */
		botIsReady: RequiredParams<'botUserTag' | 'PMID'>
		/**
		 * R​e​g​i​s​t​e​r​e​d​ ​a​l​l​ ​c​o​m​m​a​n​d​s​ ​o​n​l​i​n​e
		 */
		registeredCommandsOnline: string
		/**
		 * R​e​s​u​m​i​n​g​ ​s​l​a​s​h​ ​c​o​m​m​a​n​d​s​…
		 */
		resumingSlashCommands: string
		/**
		 * L​o​a​d​e​d​ ​a​l​l​ ​v​o​c​a​b​u​l​a​r​y
		 */
		loadedVocab: string
		/**
		 * M​o​u​n​t​e​d​ ​c​l​i​e​n​t
		 */
		mountedClient: string
	}
	etc: {
		notImplemented: {
			/**
			 * U​s​i​n​g​ ​p​r​e​m​i​u​m​ ​c​o​m​m​a​n​d​s​ ​i​s​ ​n​o​t​ ​y​e​t​ ​s​u​p​p​o​r​t​e​d​ ​i​n​ ​D​M​.​ ​S​o​r​r​y​!
			 */
			premiumCommandsAreCurrentlyNotSupportedInDm: string
		}
		fragments: {
			/**
			 * {​p​r​e​f​i​x​}​:​ ​{​s​u​f​f​i​x​}
			 * @param {unknown} prefix
			 * @param {unknown} suffix
			 */
			separatedWithDoubleColumns: RequiredParams<'prefix' | 'suffix'>
		}
	}
	guardsFeedbacks: {
		/**
		 * T​h​i​s​ ​c​o​m​m​a​n​d​ ​i​s​ ​r​e​s​e​r​v​e​d​ ​t​o​ ​p​r​e​m​i​u​m​ ​u​s​e​r​s​.
		 */
		premiumOnlyCommand: string
	}
	pushNotifications: {
		/**
		 * H​e​y​ ​{​m​e​m​b​e​r​I​d​M​a​g​i​c​S​t​r​i​n​g​}​,​ ​c​h​e​c​k​ ​t​h​i​s​!
		 * @param {unknown} memberIdMagicString
		 */
		greet: RequiredParams<'memberIdMagicString'>
	}
	warnings: {
		/**
		 * W​A​R​N​I​N​G​!
		 */
		title: string
	}
	vocab: {
		/**
		 * T​h​e​ ​m​a​x​i​m​u​m​ ​l​e​n​g​t​h​ ​o​f​ ​t​h​e​ ​d​u​r​a​t​i​o​n​ ​o​p​t​i​o​n​ ​t​e​x​t​ ​w​e​ ​a​c​c​e​p​t​ ​i​s​:​ ​3​0​ ​c​h​a​r​a​c​t​e​r​s​.
		 */
		acceptedMaximumDurationStringLength: string
		/**
		 * D​i​s​c​o​r​d​ ​I​D​ ​o​r​ ​p​i​n​g​ ​o​f​ ​t​h​e​ ​m​e​m​b​e​r
		 */
		memberSlashCommandOptionDescription: string
		/**
		 * D​i​s​c​o​r​d​ ​I​D​ ​o​r​ ​p​i​n​g​ ​o​f​ ​t​h​e​ ​u​s​e​r
		 */
		userSlashCommandOptionDescription: string
		/**
		 * I​'​v​e​ ​f​a​i​l​e​d​.​ ​P​l​e​a​s​e​,​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		failedToInteract: string
		/**
		 * T​h​i​s​ ​u​s​e​r​ ​i​s​ ​n​o​t​ ​i​n​ ​t​h​e​ ​g​u​i​l​d​.
		 */
		userNotInGuild: string
		/**
		 * P​o​w​e​r​e​d​ ​b​y​ ​W​P​M​ ​B​o​t
		 */
		poweredByWatermark: string
		/**
		 * T​h​i​s​ ​v​a​l​u​e​ ​i​s​ ​i​n​c​o​r​r​e​c​t​!
		 */
		thisValueIsIncorrect: string
		/**
		 * n​o​ ​r​e​a​s​o​n​ ​p​r​o​v​i​d​e​d
		 */
		reasonNotSpecified: string
		/**
		 * p​l​e​a​s​e​,​ ​t​r​y​ ​a​g​a​i​n
		 */
		pleaseTryAgain: string
		/**
		 * W​P​M​ ​B​o​t
		 */
		discordBotName: string
		/**
		 * p​e​r​m​i​s​s​i​o​n
		 */
		permission: string
		/**
		 * m​o​d​e​r​a​t​o​r
		 */
		moderator: string
		/**
		 * w​a​r​n​e​d
		 */
		warned: string
		/**
		 * d​u​r​a​t​i​o​n
		 */
		duration: string
		/**
		 * c​o​n​f​i​r​m
		 */
		confirm: string
		/**
		 * c​h​a​n​n​e​l
		 */
		channel: string
		/**
		 * p​r​e​m​i​u​m
		 */
		premium: string
		/**
		 * D​i​s​c​o​r​d
		 */
		discord: string
		/**
		 * c​a​n​c​e​l
		 */
		cancel: string
		/**
		 * v​a​n​i​t​y
		 */
		vanity: string
		/**
		 * c​o​n​f​i​g
		 */
		config: string
		/**
		 * r​e​a​s​o​n
		 */
		reason: string
		/**
		 * m​e​m​b​e​r
		 */
		member: string
		/**
		 * g​r​e​e​t
		 */
		greet: string
		/**
		 * s​t​a​l​e
		 */
		stale: string
		/**
		 * g​u​i​l​d
		 */
		guild: string
		/**
		 * m​u​t​e
		 */
		mute: string
		/**
		 * r​o​l​e
		 */
		role: string
		/**
		 * k​i​c​k
		 */
		kick: string
		/**
		 * u​s​e​r
		 */
		user: string
		/**
		 * w​a​r​n
		 */
		warn: string
		/**
		 * b​a​n
		 */
		ban: string
	}
}

export type TranslationFunctions = {
	errors: {
		muteCallback: {
			followUpFeedback: {
				/**
				 * I don't have the permissions to mute {memberIdMagicString} (member of: {guildName}). Try to move my role up in the roles list of your guild.
			https://support.discord.com/hc/en-us/articles/214836687-Role-Management-101
			Also, double check that I have the permission to timeout members on your Discord guild.
				 */
				botIsMissingPermissions: (arg: { guildName: unknown, memberIdMagicString: unknown }) => LocalizedString
				misusages: {
					warnings: {
						/**
						 * Your mute hasn't been applied to the member {memberIdMagicString} — {guildName}!
						 */
						yourMuteHasNotBeenApplied: (arg: { guildName: unknown, memberIdMagicString: unknown }) => LocalizedString
					}
				}
				/**
				 * I've failed to mute {memberIdMagicString} (member of: {guildName}). Please, try again.
				 */
				failedToInteract: (arg: { guildName: unknown, memberIdMagicString: unknown }) => LocalizedString
				/**
				 * {memberIdMagicString} is already muted (member of: {guildName}).
				 */
				thisMemberIsAlreadyMuted: (arg: { guildName: unknown, memberIdMagicString: unknown }) => LocalizedString
				/**
				 * So cute! You tried to mute me?
			Noped out your command.
			{youtubeMemeLink}
				 */
				triedToMuteBot: (arg: { youtubeMemeLink: unknown }) => LocalizedString
				/**
				 * You can't mute {memberIdMagicString} (member of: {guildName}).
				 */
				youCantMuteThisMember: (arg: { guildName: unknown, memberIdMagicString: unknown }) => LocalizedString
				/**
				 * You tried to mute yourself! You're a bit too chatty at the moment?
				 */
				triedToMuteYourself: () => LocalizedString
			}
		}
		banCallback: {
			followUpFeedback: {
				/**
				 * I don't have the permissions to ban {userIdMagicString} ({guildName}). Try to move my role up in the roles list of your guild.
			https://support.discord.com/hc/en-us/articles/214836687-Role-Management-101
			Also, double check that I have the permission to ban users on your Discord guild.
				 */
				botIsMissingPermissions: (arg: { guildName: unknown, userIdMagicString: unknown }) => LocalizedString
				misusages: {
					warnings: {
						/**
						 * Your ban hasn't been applied to the user {userIdMagicString} — {guildName}!
						 */
						yourBanHasNotBeenApplied: (arg: { guildName: unknown, userIdMagicString: unknown }) => LocalizedString
					}
				}
				/**
				 * I've failed to ban {userIdMagicString} ({guildName}). Please, try again.
				 */
				failedToInteract: (arg: { guildName: unknown, userIdMagicString: unknown }) => LocalizedString
				/**
				 * The user {userIdMagicString} is already banned ({guildName}).
				 */
				thisUserIsAlreadyBanned: (arg: { guildName: unknown, userIdMagicString: unknown }) => LocalizedString
				/**
				 * How dare you?!
			Noped out your command.
			{youtubeMemeLink}
				 */
				triedToBanBot: (arg: { youtubeMemeLink: unknown }) => LocalizedString
				/**
				 * You tried to ban yourself! Wanna hug?
				 */
				triedToBanYourself: () => LocalizedString
				/**
				 * You can't ban this user.
				 */
				youCantBanThisUser: () => LocalizedString
			}
		}
		kickCallback: {
			followUpFeedback: {
				/**
				 * I don't have the permissions to kick {memberIdMagicString} (member of: {guildName}). Try to move my role up in the roles list of your guild.
			https://support.discord.com/hc/en-us/articles/214836687-Role-Management-101
			Also, double check that I have the permission to kick members on your Discord guild.
				 */
				botIsMissingPermissions: (arg: { guildName: unknown, memberIdMagicString: unknown }) => LocalizedString
				/**
				 * I've failed to kick {memberIdMagicString} (member of: {guildName}). Please, try again.
				 */
				failedToInteract: (arg: { guildName: unknown, memberIdMagicString: unknown }) => LocalizedString
				/**
				 * Awwww… You tried to kick me?
			Noped out your command.
			{youtubeMemeLink}
				 */
				triedToKickBot: (arg: { youtubeMemeLink: unknown }) => LocalizedString
				/**
				 * You tried to kick yourself! Feeling sad today?
				 */
				triedToKickYourself: () => LocalizedString
				/**
				 * You can't kick this member.
				 */
				youCantKickThisMember: () => LocalizedString
			}
		}
		warnCallback: {
			followUpFeedback: {
				/**
				 * I don't have the permissions to warn {memberIdMagicString} (member of: {guildName}). Try to move my role up in the roles list of your guild.
			https://support.discord.com/hc/en-us/articles/214836687-Role-Management-101
				 */
				botIsMissingPermissions: (arg: { guildName: unknown, memberIdMagicString: unknown }) => LocalizedString
				/**
				 * I've failed to warn {memberIdMagicString} (member of: {guildName}). Please, try again.
				 */
				failedToInteract: (arg: { guildName: unknown, memberIdMagicString: unknown }) => LocalizedString
				/**
				 * You evil! You really thought I will let you warn me?
			Noped out your command.
			{youtubeMemeLink}
				 */
				triedToWarnBot: (arg: { youtubeMemeLink: unknown }) => LocalizedString
				/**
				 * You tried to warn yourself! Are you feeling cheeky today?
				 */
				triedToWarnYourself: () => LocalizedString
				/**
				 * You can't warn this member.
				 */
				youCantWarnThisMember: () => LocalizedString
			}
		}
		greetCallback: {
			followUpFeedback: {
				/**
				 * You have reached the limit of configurable greets for your guild. Upgrade to premium to create up to {premiumMaxGreetsAmount} greets.
				 */
				usedAllYourGreetCreditsEphemeralWithFreemiumPlan: (arg: { premiumMaxGreetsAmount: unknown }) => LocalizedString
				/**
				 * You already have configured {premiumMaxGreetsAmount} greets for your guild. Please, delete one of them before creating a new one.
				 */
				usedAllYourGreetCreditsEphemeralWithPremiumPlan: (arg: { premiumMaxGreetsAmount: unknown }) => LocalizedString
				/**
				 * I don't have the permission to post in this channel! ({channelIdMagicString})
				 */
				botIsMissingPermissions: (arg: { channelIdMagicString: unknown }) => LocalizedString
			}
		}
		vanityConfigCallback: {
			followUpFeedback: {
				/**
				 * I don't have the permissions to give the role {roleIdMagicString}. Try to move my role up in the roles list of your guild.
			https://support.discord.com/hc/fr/articles/214836687-Gestion-des-r%C3%B4les-101
				 */
				botIsMissingPermissions: (arg: { roleIdMagicString: unknown }) => LocalizedString
				/**
				 * The targeted role is {everyoneRoleIdMagicString}! Using this role here is not allowed.
				 */
				targetedRoleIsEveryone: (arg: { everyoneRoleIdMagicString: unknown }) => LocalizedString
				/**
				 * You don't have the permissions to give the role {roleIdMagicString}.
				 */
				youCantGiveThisRole: (arg: { roleIdMagicString: unknown }) => LocalizedString
			}
		}
		attemptToGetOrCreateGuild: {
			/**
			 * Both failed to retrieve an existing guild and to create a new guild!
			 */
			bothFailedToRetrieveAnExistingGuildAndToCreateANewGuild: () => LocalizedString
		}
		commons: {
			/**
			 * {funName}: can't fetch the bans of the guild.
			 */
			cantFetchGuildBans: (arg: { funName: unknown }) => LocalizedString
			/**
			 * You misused an option!
			 */
			youHaveMisusedAnOption: () => LocalizedString
		}
		guildSlashCommand: {
			/**
			 * I'm currently muted in this guild. All my commands are disabled here.
			 */
			botIsCurrentlyTimedOut: () => LocalizedString
		}
	}
	embeds: {
		helpCommand: {
			views: {
				moderation: {
					content: {
						commands: {
							warn: {
								/**
								 * Warn a member
							**member**: Discord ID or ping
							**reason?**: warn reason
								 */
								description: () => LocalizedString
							}
							mute: {
								/**
								 * Mute a member, using Discord “Timeout” feature.
							**member**: Discord ID or ping
							**duration**: mute length (e.g. `5s`, `5m`, `5h`, or `5d`)
							**reason?**: mute reason
								 */
								description: () => LocalizedString
							}
							kick: {
								/**
								 * Kick a member
							**member**: Discord ID or ping
							**reason?**: mute reason
								 */
								description: () => LocalizedString
							}
							ban: {
								/**
								 * Ban a member
							**member**: Discord ID or ping
							**reason?**: ban reason
							**duration?**: ban length (e.g. `1d`, `36h`, or `1y`)
							**delete-messages?**: deletes the messages history of the banned user, using a duration (e.g. `5m`, `5h`, or `5d`)
								 */
								description: () => LocalizedString
							}
						}
						trailingTrivia: () => LocalizedString
					}
					/**
					 * Moderation
					 */
					title: () => LocalizedString
				}
				defaultView: {
					/**
					 * Below, you'll find a menu with categories, which in turn contain **all commands** for WPM Bot.
					 */
					description: () => LocalizedString
					/**
					 * WPM Bot help panel
					 */
					title: () => LocalizedString
				}
			}
			selectMenuOptions: {
				defaultView: {
					/**
					 * Go back to the home screen
					 */
					description: () => LocalizedString
					/**
					 * Home
					 */
					label: () => LocalizedString
				}
				moderation: {
					/**
					 * Moderation commands
					 */
					description: () => LocalizedString
					/**
					 * Moderation
					 */
					label: () => LocalizedString
				}
			}
			/**
			 * Make your selection here
			 */
			selectMenuPlaceholder: () => LocalizedString
		}
		vanityConfigCommand: {
			dangerousPermsWarning: {
				/**
				 * By confirming this action, you will validate that the members of your guild will be offered the role {roleIdMagicString}, which offers sensitive permissions:
				 */
				description: (arg: { roleIdMagicString: unknown }) => LocalizedString
				/**
				 * The role you will assign with this config is a sensitive role!
				 */
				title: () => LocalizedString
			}
		}
		'greet-info': {
			/**
			 * Renew your premium to manage up to {premiumMaxGreetsAmount} greets.
			 */
			premiumRenewal: (arg: { premiumMaxGreetsAmount: unknown }) => LocalizedString
			/**
			 * Upgrade to premium to create up to {premiumMaxGreetsAmount} greets.
			 */
			premiumAd: (arg: { premiumMaxGreetsAmount: unknown }) => LocalizedString
			/**
			 * No greet has been set up on this guild at the moment.
			 */
			noGreetYet: () => LocalizedString
			/**
			 * Greet channels
			 */
			title: () => LocalizedString
		}
		muteCommand: {
			/**
			 * You've been muted over {limit} {{time|times}}.
			 */
			mutesAmountOverLimit: (arg: { limit: string | number | boolean }) => LocalizedString
			/**
			 * You've been muted {mutesAmount} {{time|times}}.
			 */
			mutesAmount: (arg: { mutesAmount: string | number | boolean }) => LocalizedString
			/**
			 * Moderator
			 */
			reportAuthorLabel: () => LocalizedString
			/**
			 * End: {countdownMagicString}
			 */
			until: (arg: { countdownMagicString: unknown }) => LocalizedString
			/**
			 * You've been muted!
			 */
			headline: () => LocalizedString
		}
		banCommand: {
			/**
			 * You've been banned over {limit} {{time|times}}.
			 */
			bansAmountOverLimit: (arg: { limit: string | number | boolean }) => LocalizedString
			/**
			 * You've been banned {bansAmount} {{time|times}}.
			 */
			bansAmount: (arg: { bansAmount: string | number | boolean }) => LocalizedString
			/**
			 * Moderator
			 */
			reportAuthorLabel: () => LocalizedString
			/**
			 * End: {countdownMagicString}
			 */
			until: (arg: { countdownMagicString: unknown }) => LocalizedString
			/**
			 * You've been banned!
			 */
			headline: () => LocalizedString
		}
		warnCommand: {
			/**
			 * You have been warned over {limit} {{time|times}}.
			 */
			warnsAmountOverLimit: (arg: { limit: string | number | boolean }) => LocalizedString
			/**
			 * You have been warned {warnsAmount} {{time|times}}.
			 */
			warnsAmount: (arg: { warnsAmount: string | number | boolean }) => LocalizedString
			/**
			 * Moderator
			 */
			reportAuthorLabel: () => LocalizedString
			/**
			 * You've been warned!
			 */
			headline: () => LocalizedString
		}
		kickCommand: {
			/**
			 * You've been kicked over {limit} {{time|times}}.
			 */
			kicksAmountOverLimit: (arg: { limit: string | number | boolean }) => LocalizedString
			/**
			 * You've been kicked {kicksAmount} {{time|times}}.
			 */
			kicksAmount: (arg: { kicksAmount: string | number | boolean }) => LocalizedString
			/**
			 * Moderator
			 */
			reportAuthorLabel: () => LocalizedString
			/**
			 * You've been kicked!
			 */
			headline: () => LocalizedString
		}
		commons: {
			/**
			 * Powered by WPM Bot
			 */
			footerText: () => LocalizedString
		}
	}
	slashCommands: {
		ban: {
			options: {
				'delete-messages': {
					/**
					 * Deletes the messages history of the banned user (minimum: 1m, maximum: 7d)
					 */
					description: () => LocalizedString
					/**
					 * delete-messages
					 */
					name: () => LocalizedString
				}
				duration: {
					/**
					 * Ban duration (minimum: 1d, maximum: 100y)
					 */
					description: () => LocalizedString
					/**
					 * duration
					 */
					name: () => LocalizedString
				}
				reason: {
					/**
					 * Ban reason
					 */
					description: () => LocalizedString
					/**
					 * reason
					 */
					name: () => LocalizedString
				}
				user: {
					/**
					 * Discord ID or ping of the user
					 */
					description: () => LocalizedString
					/**
					 * user
					 */
					name: () => LocalizedString
				}
			}
			/**
			 * Ban a member
			 */
			description: () => LocalizedString
			/**
			 * ban
			 */
			name: () => LocalizedString
		}
		mute: {
			options: {
				duration: {
					/**
					 * Mute duration (minimum: 5s, maximum: 28d)
					 */
					description: () => LocalizedString
					/**
					 * duration
					 */
					name: () => LocalizedString
				}
				member: {
					/**
					 * Discord ID or ping of the member
					 */
					description: () => LocalizedString
					/**
					 * member
					 */
					name: () => LocalizedString
				}
				reason: {
					/**
					 * Mute reason
					 */
					description: () => LocalizedString
					/**
					 * reason
					 */
					name: () => LocalizedString
				}
			}
			/**
			 * Mute a member, using Discord “Timeout” feature
			 */
			description: () => LocalizedString
			/**
			 * mute
			 */
			name: () => LocalizedString
		}
		warn: {
			options: {
				member: {
					/**
					 * Discord ID or ping of the member
					 */
					description: () => LocalizedString
					/**
					 * member
					 */
					name: () => LocalizedString
				}
				reason: {
					/**
					 * Warn reason
					 */
					description: () => LocalizedString
					/**
					 * reason
					 */
					name: () => LocalizedString
				}
			}
			/**
			 * Warn a member
			 */
			description: () => LocalizedString
			/**
			 * warn
			 */
			name: () => LocalizedString
		}
		kick: {
			options: {
				member: {
					/**
					 * Discord ID or ping of the member
					 */
					description: () => LocalizedString
					/**
					 * member
					 */
					name: () => LocalizedString
				}
				reason: {
					/**
					 * Kick reason
					 */
					description: () => LocalizedString
					/**
					 * reason
					 */
					name: () => LocalizedString
				}
			}
			/**
			 * Kick a member
			 */
			description: () => LocalizedString
			/**
			 * kick
			 */
			name: () => LocalizedString
		}
		ping: {
			options: {
				'meaningless-choice': {
					choices: {
						/**
						 * useless
						 */
						lmao: () => LocalizedString
						/**
						 * useless
						 */
						lol: () => LocalizedString
					}
					/**
					 * useless
					 */
					description: () => LocalizedString
					/**
					 * useless-choice
					 */
					name: () => LocalizedString
				}
			}
			/**
			 * Bot latency (ms).
			 */
			description: () => LocalizedString
			/**
			 * ping
			 */
			name: () => LocalizedString
		}
		'config-vanity': {
			options: {
				role: {
					/**
					 * Role to give to the members sharing the vanity link in their status
					 */
					description: () => LocalizedString
					/**
					 * role
					 */
					name: () => LocalizedString
				}
				vanity: {
					/**
					 * Custom invite link (discord.gg/example)
					 */
					description: () => LocalizedString
					/**
					 * vanity
					 */
					name: () => LocalizedString
				}
			}
			/**
			 * Choose an invitation link and a role to reward members who share it.
			 */
			description: () => LocalizedString
			/**
			 * vanity
			 */
			name: () => LocalizedString
		}
		config: {
			/**
			 * TBD
			 */
			description: () => LocalizedString
			/**
			 * config
			 */
			name: () => LocalizedString
			options: {
			}
		}
		'greet-toggle': {
			options: {
				channel: {
					/**
					 * Lorem ipsum dolor sit amet - TBD
					 */
					description: () => LocalizedString
					/**
					 * channel
					 */
					name: () => LocalizedString
				}
			}
			/**
			 * Lorem ipsum dolor sit amet - TBD
			 */
			description: () => LocalizedString
			/**
			 * toggle
			 */
			name: () => LocalizedString
		}
		'greet-infos': {
			/**
			 * Lorem ipsum dolor sit amet - TBD
			 */
			description: () => LocalizedString
			/**
			 * infos
			 */
			name: () => LocalizedString
			options: {
			}
		}
		greet: {
			/**
			 * Lorem ipsum dolor sit amet - TBD
			 */
			description: () => LocalizedString
			options: {
			}
			/**
			 * greet
			 */
			name: () => LocalizedString
		}
		help: {
			/**
			 * Display all commands
			 */
			description: () => LocalizedString
			/**
			 * help
			 */
			name: () => LocalizedString
			options: {
			}
		}
	}
	tutorials: {
		usage: {
			durationOption: {
				examples: {
					banDeleteMessagesHistoryDurationLimit: {
						/**
						 * `1m`: delete the user's messages for one minute before the ban.
					`1h`: delete the user's messages for one hour before the ban.
					`1d`: delete the user's messages for one day before the ban.
						 */
						gist: () => LocalizedString
						/**
						 * Minimum: **1 minute** (`1m`), maximum: **7 days** (`7d`).
					The maximum length of the duration option text we accept is: 30 characters.
						 */
						additionalInformations: () => LocalizedString
					}
					mute: {
						/**
						 * Minimum: **5 seconds** (`5s`), maximum: **28 days** (`28d`).
					The maximum length of the duration option text we accept is: 30 characters.
						 */
						additionalInformations: () => LocalizedString
						/**
						 * `5s`: mute for 5 seconds.
					`5m`: mute for 5 minutes.
					`5h`: mute for 5 hours.
					`5d`: mute for 5 days.
						 */
						gist: () => LocalizedString
					}
					ban: {
						/**
						 * Minimum: **1 day** (`1d`), maximum: **100 years** (`100y`).
					The maximum length of the duration option text we accept is: 30 characters.
						 */
						additionalInformations: () => LocalizedString
						/**
						 * `1d`: ban for 1 day.
					`1y`: ban for 1 year.
						 */
						gist: () => LocalizedString
					}
				}
				informationEmbed: {
					/**
					 * “`Duration`” option usage with WPM Bot
					 */
					title: () => LocalizedString
					/**
					 * Specifying a duration of:
				- `{userDurationInput}`
					 */
					'with': (arg: { userDurationInput: unknown }) => LocalizedString
				}
			}
			vanityConfig: {
				examples: {
					needle: {
						/**
						 * The maximum length of the vanity code option's `MY-INVITE-CODE` block text we accept is: 25 characters.
					Notice that only alphanumeric characters and dashes are allowed in this block.
						 */
						additionalInformations: () => LocalizedString
						/**
						 * `https://discord.gg/MY-INVITE-CODE`
					`discord.gg/MY-INVITE-CODE`
					`.gg/MY-INVITE-CODE`
					`gg/MY-INVITE-CODE`
					`/MY-INVITE-CODE`
					`MY-INVITE-CODE`
						 */
						gist: () => LocalizedString
					}
				}
				informationEmbed: {
					/**
					 * Vanity config usage with WPM Bot
					 */
					title: () => LocalizedString
					/**
					 * Specifying a vanity code of:
				- `{vanityCode}`
					 */
					'with': (arg: { vanityCode: unknown }) => LocalizedString
				}
			}
		}
		/**
		 * You tried to use the command:
	- `/{commandName}`
	With the option:
	- `{option}`
		 */
		usecase: (arg: { commandName: unknown, option: unknown }) => LocalizedString
		/**
		 * Examples of usage
		 */
		examplesHeadline: () => LocalizedString
		/**
		 * Good to know
		 */
		goodToKnowHeadline: () => LocalizedString
		/**
		 * Help notice
		 */
		helpTitle: () => LocalizedString
	}
	permissions: {
		/**
		 * Mention @everyone, @here, and All Roles
		 */
		MentionEveryone: () => LocalizedString
		/**
		 * Timeout Members
		 */
		ModerateMembers: () => LocalizedString
		/**
		 * Manage Channels
		 */
		ManageChannels: () => LocalizedString
		/**
		 * Deafen Members
		 */
		DeafenMembers: () => LocalizedString
		/**
		 * Create Expressions
		 */
		CreateGuildExpressions: () => LocalizedString
		/**
		 * Manage Expressions
		 */
		ManageGuildExpressions: () => LocalizedString
		/**
		 * Kick Members
		 */
		KickMembers: () => LocalizedString
		/**
		 * Manage Roles
		 */
		ManageRoles: () => LocalizedString
		/**
		 * Move Members
		 */
		MoveMembers: () => LocalizedString
		/**
		 * Mute Members
		 */
		MuteMembers: () => LocalizedString
		/**
		 * Ban Members
		 */
		BanMembers: () => LocalizedString
		/**
		 * Manage Nicknames
		 */
		ManageNicknames: () => LocalizedString
		/**
		 * Manage Messages
		 */
		ManageMessages: () => LocalizedString
		/**
		 * Manage Webhooks
		 */
		ManageWebhooks: () => LocalizedString
		/**
		 * Manage Threads
		 */
		ManageThreads: () => LocalizedString
		/**
		 * Administrator
		 */
		Administrator: () => LocalizedString
		/**
		 * Manage Events
		 */
		ManageEvents: () => LocalizedString
		/**
		 * Manage Server
		 */
		ManageGuild: () => LocalizedString
	}
	infos: {
		greetCallback: {
			followUpFeedback: {
				/**
				 * The greet has been removed from the channel! — {channelIdMagicString}
				 */
				greetRemoved: (arg: { channelIdMagicString: unknown }) => LocalizedString
				/**
				 * The greet has been added to the channel! — {channelIdMagicString}
				 */
				greetAdded: (arg: { channelIdMagicString: unknown }) => LocalizedString
			}
		}
		vanityConfigCallback: {
			followUpFeedback: {
				/**
				 * The vanity has been set up successfully! Members who share `{vanityCode}` in their status will receive the role {roleIdMagicString}.
				 */
				successfullyConfiguredVanity: (arg: { roleIdMagicString: unknown, vanityCode: unknown }) => LocalizedString
			}
		}
	}
	initializers: {
		/**
		 * Ready! Logged in as {botUserTag}. PMID: {PMID}.
		 */
		botIsReady: (arg: { botUserTag: unknown, PMID: unknown }) => LocalizedString
		/**
		 * Registered all commands online
		 */
		registeredCommandsOnline: () => LocalizedString
		/**
		 * Resuming slash commands…
		 */
		resumingSlashCommands: () => LocalizedString
		/**
		 * Loaded all vocabulary
		 */
		loadedVocab: () => LocalizedString
		/**
		 * Mounted client
		 */
		mountedClient: () => LocalizedString
	}
	etc: {
		notImplemented: {
			/**
			 * Using premium commands is not yet supported in DM. Sorry!
			 */
			premiumCommandsAreCurrentlyNotSupportedInDm: () => LocalizedString
		}
		fragments: {
			/**
			 * {prefix}: {suffix}
			 */
			separatedWithDoubleColumns: (arg: { prefix: unknown, suffix: unknown }) => LocalizedString
		}
	}
	guardsFeedbacks: {
		/**
		 * This command is reserved to premium users.
		 */
		premiumOnlyCommand: () => LocalizedString
	}
	pushNotifications: {
		/**
		 * Hey {memberIdMagicString}, check this!
		 */
		greet: (arg: { memberIdMagicString: unknown }) => LocalizedString
	}
	warnings: {
		/**
		 * WARNING!
		 */
		title: () => LocalizedString
	}
	vocab: {
		/**
		 * The maximum length of the duration option text we accept is: 30 characters.
		 */
		acceptedMaximumDurationStringLength: () => LocalizedString
		/**
		 * Discord ID or ping of the member
		 */
		memberSlashCommandOptionDescription: () => LocalizedString
		/**
		 * Discord ID or ping of the user
		 */
		userSlashCommandOptionDescription: () => LocalizedString
		/**
		 * I've failed. Please, try again.
		 */
		failedToInteract: () => LocalizedString
		/**
		 * This user is not in the guild.
		 */
		userNotInGuild: () => LocalizedString
		/**
		 * Powered by WPM Bot
		 */
		poweredByWatermark: () => LocalizedString
		/**
		 * This value is incorrect!
		 */
		thisValueIsIncorrect: () => LocalizedString
		/**
		 * no reason provided
		 */
		reasonNotSpecified: () => LocalizedString
		/**
		 * please, try again
		 */
		pleaseTryAgain: () => LocalizedString
		/**
		 * WPM Bot
		 */
		discordBotName: () => LocalizedString
		/**
		 * permission
		 */
		permission: () => LocalizedString
		/**
		 * moderator
		 */
		moderator: () => LocalizedString
		/**
		 * warned
		 */
		warned: () => LocalizedString
		/**
		 * duration
		 */
		duration: () => LocalizedString
		/**
		 * confirm
		 */
		confirm: () => LocalizedString
		/**
		 * channel
		 */
		channel: () => LocalizedString
		/**
		 * premium
		 */
		premium: () => LocalizedString
		/**
		 * Discord
		 */
		discord: () => LocalizedString
		/**
		 * cancel
		 */
		cancel: () => LocalizedString
		/**
		 * vanity
		 */
		vanity: () => LocalizedString
		/**
		 * config
		 */
		config: () => LocalizedString
		/**
		 * reason
		 */
		reason: () => LocalizedString
		/**
		 * member
		 */
		member: () => LocalizedString
		/**
		 * greet
		 */
		greet: () => LocalizedString
		/**
		 * stale
		 */
		stale: () => LocalizedString
		/**
		 * guild
		 */
		guild: () => LocalizedString
		/**
		 * mute
		 */
		mute: () => LocalizedString
		/**
		 * role
		 */
		role: () => LocalizedString
		/**
		 * kick
		 */
		kick: () => LocalizedString
		/**
		 * user
		 */
		user: () => LocalizedString
		/**
		 * warn
		 */
		warn: () => LocalizedString
		/**
		 * ban
		 */
		ban: () => LocalizedString
	}
}

export type Formatters = {}
