export enum EIncrementCounterResult {
  UNEXPECTED_BEHAVIOR = 'UNEXPECTED_BEHAVIOR',
  INCREMENTED = 'INCREMENTED',
  FORBIDDEN = 'FORBIDDEN'
}

export enum EIsLockedCounter {
  UNEXPECTED_BEHAVIOR = 'UNEXPECTED_BEHAVIOR',
  UNLOCKED = 'UNLOCKED',
  LOCKED = 'LOCKED'
}
